set nocompatible

" configure nice defaults
syntax enable
filetype plugin on
set number
set wildmenu

call plug#begin('~/.vim/plugged')
  Plug 'scrooloose/nerdtree'
  Plug 'w0rp/ale'
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
  Plug 'posva/vim-vue'
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'tpope/vim-commentary'
call plug#end()

let g:deoplete#enable_at_startup = 1
"let g:deoplete#sources = {'_': 'ale'}
call deoplete#custom#option('sources', {
\ '_': ['ale', 'buffer'],
\})

let g:ale_fixers = {
                        \       '*': ['prettier']
                        \}

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v(node_modules|[\/]\.(git|hg|svn))$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4
autocmd FileType go setlocal expandtab shiftwidth=4 softtabstop=4

set expandtab
