set nocompatible

" configure nice defaults
syntax enable
filetype plugin on
set number
set wildmenu

call plug#begin('~/.vim/plugged')
  Plug 'scrooloose/nerdtree'
  Plug 'w0rp/ale'
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

let g:deoplete#enable_at_startup = 1
"let g:deoplete#sources = {'_': 'ale'}
call deoplete#custom#option('sources', {
\ '_': ['ale', 'buffer'],
\})


autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4
autocmd FileType go setlocal expandtab shiftwidth=4 softtabstop=4

set expandtab
